version: "3"

services:
  dev_db:
    image: postgres
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"

  dev_web:
    build:
      context: ../
      dockerfile: Dockerfile
    command: sleep infinity
    environment:
      - "DJANGO_SETTINGS_MODULE=private_diary.settings_dev"
    volumes:
      - ..:/workspace
    ports:
      - "8000:8000"
    depends_on:
      - dev_db
